project:
  type: website

website:
  title: "An Le"
  favicon: images/my_logo.jpg
  navbar:
    logo: images/my_logo.jpg
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Profile
      - projects.qmd

format:
  html:
    theme:
      light: [cosmo, custom.scss, custom_light.scss]
      dark: [cosmo, custom.scss, custom_dark.scss]
    toc: false
    page-layout: full
    include-after-body:
      # I don't want the date and authors in the project listings to be all caps
      - text: |
          <style>
          .quarto-grid-item .listing-date,
          .quarto-grid-item .listing-author {
            text-transform: none;
          }
          </style>