---
title: "Profile"
format:
  html:
    include-in-header:
      text: |
        <style>
        
        <!-- Remove borders from tables for a resume format -->
        table {
          border-collapse: collapse;
        }
        table, .table, th, td, tr, th, td {
          border: none !important;
          border-top: none !important;
          border-bottom: none !important;
        }
        .table-striped>tbody>tr:nth-of-type(odd)>* {
          box-shadow: none !important;
        }
        
        </style>
---

::: {style="text-align: center;"}
# Thai An Le

{{< fa envelope >}} [thaianle1102@gmail.com](mailto:thaianle1102@gmail.com) &emsp;&emsp;&emsp; {{< fa envelope >}} [ale2@bates.edu](mailto:ale2@bates.edu) &emsp;&emsp;&emsp; {{< fa brands linkedin >}} [Thai An Le](https://www.linkedin.com/in/thaianle/) &emsp;&emsp;&emsp; {{< fa brands github >}} [thaianle](https://github.com/thaianle)
:::

## Education

```{=html}
<head>

<!-- Remove borders from table -->
<style>
  table {
    border-collapse: collapse;
    border: none;
  }
  th, td {
    border: none;
  }
</style>

<!-- 2-column table format for resume -->
<table style="font-size:15px;">
  <tr>
    <td style="width:70%; text-align:left;"><a href="https://www.bates.edu/"><strong>Bates College</strong></a><br><em>Economics and Mathematics Major, Digital and Computational Studies Minor</em></td>
    <td style="width:30%; text-align:right;"><strong>Lewiston, ME</strong><br><em>Expected Graduation: May 2028</em></td>
  </tr>
  <tr>
    <td colspan="2">
    <ul>
      <li><strong>Relevant Coursework:</strong> Experimental Economics, Mathematical Image Processing, Introduction to Abstraction <em>(proof-based mathematics course)</em>, Computing for Insight</li>
      <li><strong>Clubs and Societies:</strong> Data Club, Math Club, International Club</li>
    </ul>
    </td>
  </tr>
</table>

</head>
```

## Research Experience

```{=html}
<head>

<style>
  table {
    border-collapse: collapse;
    border: none;
  }
  th, td {
    border: none;
  }
</style>

<table style="font-size:15px;">

  <tr>
    <td style="width:70%; text-align:left;"><a href="https://www.cmu.edu/dietrich/statistics-datascience/engagement/summer/cmsa-camp.html"><strong>Carnegie Mellon Sports Analytics Camp (CMSACamp)</strong></a><br><em>Undergraduate Research Fellow</em></td>
    <td style="width:30%; text-align:right;"><strong>Pittsburgh, PA</strong><br><em>Jun 2026 - Jul 2026</em></td>
  </tr>
  <tr>
    <td colspan="2">
    <strong>Advisor: Katerina Wu (University of Pittsburgh)</strong><br><ul>
      <li>Selected among 16 undergraduate rising juniors and seniors nationwide for a 2-month sports analytics research experience at Carnegie Mellon University.</li>
      <li>Attend daily lectures on data analysis and statistical learning applied to sports; collaborate with other research fellows and an external industry partner to develop a data analysis and modeling project.</li>
    </ul>
    </td>
  </tr>

  <tr>
    <td style="width:70%; text-align:left;"><a href="https://www.sandragoff.com/glee"><strong>Goff Lab for Experimental Economics (GLEE) at Bates College</strong></a><br><em>Economic Research Assistant</em></td>
    <td style="width:30%; text-align:right;"><strong>Lewiston, ME</strong><br><em>Feb 2026 - Present</em></td>
  </tr>
  <tr>
    <td colspan="2">
    <strong>PI: Sandra Goff (Bates College)</strong><br><ul>
      <li>Implemented economic experiments to assess how the framing of negative externalities associated with a transaction influences market participants' attitudes and decision-making.</li>
      <li>Collaborated with professors Sandra Goff (Bates College) and John Ifcher (Santa Clara University) to adapt related in-person experiments into a one-shot survey on Qualtrics and an interactive simulation on oTree.</li>
    </ul>
    </td>
  </tr>

</table>

</head>
```

## Presentations

**Le, A.**, Lucas, K. (Forthcoming). _The Effects of Transferring on Player Performance: An Analysis on NCAA Division I Men’s Basketball_ \[Conference presentation\]. Carnegie Mellon Sports Analytics Conference, Pittsburgh, PA, United States. Scheduled 2026, October 24.

**Le, A.**, Lucas, K. (2026, July 24). _The Effects of Transferring on Player Performance: An Analysis on NCAA Division I Men’s Basketball_ \[Oral and poster presentation\]. Carnegie Mellon Sports Analytics Camp, Pittsburgh, PA, United States. <https://www.stat.cmu.edu/cmsac/sure/2026/showcase/ncaa_transfers/poster.pdf>

## Work Experience

```{=html}
<head>

<style>
  table {
    border-collapse: collapse;
    border: none;
  }
  th, td {
    border: none;
  }
</style>

<table style="font-size:15px;">

  <tr>
    <td style="width:70%; text-align:left;"><a href="https://www.bates.edu/student-writing-language-center/"><strong>Bates College Student Writing and Language Center</strong></a><br><em>Writing Fellow</em></td>
    <td style="width:30%; text-align:right;"><strong>Lewiston, ME</strong><br><em>Sep 2025 - Present</em></td>
  </tr>
  <tr>
    <td colspan="2">
    <ul>
      <li>Provided personalized feedback and guidance for writing assignments at all stages of the writing process, across multiple genres and disciplines.</li>
      <li>Developed strategies drawn from specialized writing and pedagogy training to help students enhance their writing skills and navigate the writing curriculum at Bates College.</li>
    </ul>
    </td>
  </tr>
  
  <tr>
    <td style="width:70%; text-align:left;"><a href="https://www.bates.edu/mathematics/"><strong>Bates College Department of Mathematics</strong></a><br><em>Mathematics/Digital and Computational Studies Grader</em></td>
    <td style="width:30%; text-align:right;"><strong>Lewiston, ME</strong><br><em>Jan 2025 - Dec 2025</em></td>
  </tr>
  <tr>
    <td colspan="2">
    <ul>
      <li>Graded and gave detailed feedback on weekly in-class and homework assignments for 3 class sections with ~80 students in total.</li>
      <li>Gained hands-on experience in cleaning and visualizing data with R, reporting analysis results with R Markdown, and managing projects with GitHub.</li>
    </ul>
    </td>
  </tr>

</table>

</head>
```

## Leadership & Extracurricular Activities

```{=html}
<head>

<style>
  table {
    border-collapse: collapse;
    border: none;
  }
  th, td {
    border: none;
  }
</style>

<table style="font-size:15px;">

  <tr>
    <td style="width:70%; text-align:left;"><a href="https://www.bates.edu/education/"><strong>Bates College Department of Education</strong></a><br><em>Fieldwork Participant</em></td>
    <td style="width:30%; text-align:right;"><strong>Auburn, ME</strong><br><em>Sep 2025 - Dec 2025</em></td>
  </tr>
  <tr>
    <td colspan="2">
    <ul>
      <li>Observed and assisted a teacher in algebra and pre-calculus classes at Edward Little High School for 3.5 hours per week as part of an Education course at Bates College.</li>
      <li>Collaborated with the host teacher to provide targeted support to students in small-group settings and prepare the necessary instructional materials.</li>
    </ul>
    </td>
  </tr>

  <tr>
    <td style="width:70%; text-align:left;"><a href="https://www.bates.edu/harward/"><strong>Bates College Harward Center for Community Partnerships</strong></a><br><em>Community-Engaged Learning Participant</em></td>
    <td style="width:30%; text-align:right;"><strong>Lewiston, ME</strong><br><em>Apr 2025 - May 2025</em></td>
  </tr>
  <tr>
    <td colspan="2">
    <ul>
      <li>Designed and conducted two 30-minute creative writing workshops for 30 students at Geiger Elementary School as part of a Short Term course at Bates College.</li>
      <li>Applied understanding of the relationship between language and experience in developing lesson plans.</li>
    </ul>
    </td>
  </tr>

</table>

</head>
```

## Honors and Awards

```{=html}
<head>

<style>
  table {
    border-collapse: collapse;
    border: none;
  }
  th, td {
    border: none;
  }
</style>

<table style="font-size:15px;">

  <tr>
    <td style="width:20%; text-align:left;">Fall 2024 - Winter 2026</td>
    <td style="width:80%; text-align:left;"><strong>Dean's List for Academic Excellence</strong></td>
  </tr>

  <tr>
    <td style="width:20%; text-align:left;">Fall 2024</td>
    <td style="width:80%; text-align:left;"><a href="https://www.bates.edu/stem-scholars/"><strong>Bates STEM Scholars</strong></a> <em>(a selective cohort of students receiving extra support in exploring STEM careers)</em></td>
  </tr>

</table>

</head>
```

## Skills and Interests

```{=html}
<head>

<style>
  table {
    border-collapse: collapse;
    border: none;
  }
  th, td {
    border: none;
    padding-top: 7px;
    padding-bottom: 7px;
  }
</style>

<table style="font-size:15px;">

  <tr>
    <td style="width:20%; text-align:left;"><strong>Languages</strong></td>
    <td style="width:80%; text-align:left;">Vietnamese (Native), English (Fluent)</td>
  </tr>

  <tr>
    <td style="width:20%; text-align:left;"><strong>Programming</strong></td>
    <td style="width:80%; text-align:left;">Python, R (Advanced), Stata, SQL, git/GitHub (Intermediate), MATLAB, Qualtrics, oTree, Linux/bash (Basic)</td>
  </tr>

  <tr>
    <td style="width:20%; text-align:left;"><strong>Typesetting</strong></td>
    <td style="width:80%; text-align:left;">Microsoft Office Suite, Google Workspace (Proficient), Canva, LaTeX (Intermediate), Quarto (Basic)</td>
  </tr>

  <tr>
    <td style="width:20%; text-align:left;"><strong>Interests</strong></td>
    <td style="width:80%; text-align:left;">Teaching, Peer Tutoring, Singing, Piano, Electronic Keyboard, Soccer, Trivia</td>
  </tr>

</table>

</head>
```

<br><br>

::: {style="text-align: center;"}
_Last updated: July 26, 2026._
:::